name: hpets
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  logger: ^1.1.0
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.1
  connectivity: ^3.0.6
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  fonts:
    - family: SignikaNegative-Bold
      fonts:
        - asset: assets/fonts/SignikaNegative-Bold.ttf
    - family: SignikaNegative-Light
      fonts:
        - asset: assets/fonts/SignikaNegative-Light.ttf
    - family: SignikaNegative-Medium
      fonts:
        - asset: assets/fonts/SignikaNegative-Medium.ttf
    - family: SignikaNegative-Regular
      fonts:
        - asset: assets/fonts/SignikaNegative-Regular.ttf
    - family: SignikaNegative-SemiBold
      fonts:
        - asset: assets/fonts/SignikaNegative-SemiBold.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

